name: remote ssh command
on:
  push:
    branches:
    - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ec2-13-233-199-144.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.NEW }}
        port: 22
        script: |
          whoami
          ls
